---
AWSTemplateFormatVersion: 2010-09-09
Description: Precompile Lambda Packages - EC2 stack

Parameters:
  EnvironmentName:
    Type: String
    Description: Name of the precompiler environment
    Default: dev
  AmiID:
    Type: String
    Description: AMI Id for instance
  InstanceType:
    Type: String
    Description: Size of instance
    Default: t2.micro
  PublicSubnet0:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the public subnet
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ID of the security group
  PackageName:
    Type: String
    Description: Name of the package to install
  BucketName:
    Type: String
    Description: Name of the bucket to upload the zipped packages to
  TopicARN:
    Type: String
    Description: ARN of the SNS topic to publish notifications to

Resources:
  PrecompileInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      BlockDeviceMappings:
      - DeviceName: "/dev/xvdb"
        Ebs:
          DeleteOnTermination: True
          VolumeType: gp2
          VolumeSize:
            10
      IamInstanceProfile: !ImportValue
        Fn::Sub:
          - PrecompileInstanceProfile-${EnvironmentName}
          - { EnvironmentName: !Ref EnvironmentName }
      ImageId:
        !Ref AmiID
      InstanceType:
        !Ref InstanceType
      KeyName: !Sub
        - ${EnvironmentName}-precompile-key
        - { EnvironmentName: !Ref EnvironmentName }
      Monitoring: True
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId:
            !Ref PublicSubnet0
          GroupSet:
            - !Ref SecurityGroup
          AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value:
            !Join [ '', [ 'Precompile / ', !Ref 'AWS::StackName' ] ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Script generously lifted from https://gist.github.com/niranjv/f80fc1f488afc49845e2ff3d5df7f83b
          yum update

          # install pre-requisites
          sudo yum -y groupinstall development
          sudo yum -y install zlib-devel
          sudo yum -y install openssl-devel
          sudo yum -y install libffi-devel
          sudo yum -y install python36-devel
          sudo yum install curl git m4 ruby texinfo bzip2-devel curl-devel expat-devel ncurses-devel

          # Installing openssl-devel alone seems to result in SSL errors in pip (see https://medium.com/@moreless/pip-complains-there-is-no-ssl-support-in-python-edbdce548852)
          # Need to install OpenSSL also to avoid these errors
          wget https://github.com/openssl/openssl/archive/OpenSSL_1_0_2l.tar.gz
          tar -zxvf OpenSSL_1_0_2l.tar.gz
          cd openssl-OpenSSL_1_0_2l/

          ./config shared
          make
          sudo make install
          export LD_LIBRARY_PATH=/usr/local/ssl/lib/

          cd ..
          rm OpenSSL_1_0_2l.tar.gz
          rm -rf openssl-OpenSSL_1_0_2l/

          # Install Linuxbrew
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
          test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
          test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile
          echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.profile

          # Install nodejs
          brew install nodejs

          # install sls + plugins
          npm install -g serverless
          sls plugin install -n serverless-python-requirements

          # Install Python 3.6
          wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
          tar xJf Python-3.6.0.tar.xz
          cd Python-3.6.0

          ./configure
          make
          sudo make install

          cd ..
          rm Python-3.6.0.tar.xz
          sudo rm -rf Python-3.6.0

          # Install package via pip
          REGION=$(curl http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}')
          mkdir /root/tmp
          cd /root/tmp
          #/usr/local/bin/pip3 install ${PackageName} --no-binary ${PackageName} -t .
          /usr/local/bin/pip3 install ${PackageName} -t .
          zip -r ${PackageName}.zip .
          aws s3 cp ${PackageName}.zip s3://${BucketName}/lambda-precompile-package/packages/
          aws sns publish --topic-arn ${TopicARN} --region $REGION --message "Your package ${PackageName} has been compiled, zipped and uploaded to: https://s3-$REGION.amazonaws.com/${BucketName}/lambda-precompile-package/packages/${PackageName}.zip"
          # TODO: figure out a clean way of allowing this instance to clean up the infra stack when finished
          # aws cloudformation delete-stack --stack-name precompile-infra --region $REGION
